use std::fmt::Write as FmtWrite;
use std::path::Path;

use graphify_core::graph::CodeGraph;

/// Escapes a string for use inside a Cypher single-quoted string literal.
///
/// Replaces backslashes and single quotes with their escaped forms.
fn cypher_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

/// Writes a Neo4j Cypher import script to `path`.
///
/// The script creates one node per graph node (labelled by `NodeKind`) and one
/// relationship per edge (typed by `EdgeKind`).  All properties are included as
/// Cypher map literals.
///
/// # Panics
/// Panics if file I/O fails.
pub fn write_cypher(graph: &CodeGraph, path: &Path) {
    let mut buf = String::new();

    writeln!(buf, "// Generated by Graphify — Neo4j Cypher import script").unwrap();
    writeln!(
        buf,
        "// Nodes: {}, Edges: {}",
        graph.node_count(),
        graph.edge_count()
    )
    .unwrap();
    writeln!(buf).unwrap();

    // Nodes
    for node in graph.nodes() {
        let label = format!("{:?}", node.kind);
        let file_path = cypher_escape(&node.file_path.to_string_lossy());
        let language = format!("{:?}", node.language);
        // FEAT-021: emit `alternative_paths` as a Cypher list literal (array
        // of strings). Only written when non-empty so legacy-shape parity with
        // the JSON writer is preserved.
        if node.alternative_paths.is_empty() {
            writeln!(
                buf,
                "CREATE (:{label} {{id: '{id}', file_path: '{file_path}', language: '{language}', line: {line}, is_local: {is_local}}});",
                id = cypher_escape(&node.id),
                line = node.line,
                is_local = node.is_local,
            )
            .unwrap();
        } else {
            let alts = node
                .alternative_paths
                .iter()
                .map(|p| format!("'{}'", cypher_escape(p)))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                buf,
                "CREATE (:{label} {{id: '{id}', file_path: '{file_path}', language: '{language}', line: {line}, is_local: {is_local}, alternative_paths: [{alts}]}});",
                id = cypher_escape(&node.id),
                line = node.line,
                is_local = node.is_local,
            )
            .unwrap();
        }
    }

    writeln!(buf).unwrap();

    // Edges
    for (src, tgt, edge) in graph.edges() {
        let rel_type = format!("{:?}", edge.kind).to_uppercase();
        let conf_kind = format!("{:?}", edge.confidence_kind);
        writeln!(
            buf,
            "MATCH (a {{id: '{src}'}}), (b {{id: '{tgt}'}}) CREATE (a)-[:{rel_type} {{weight: {weight}, line: {line}, confidence: {confidence}, confidence_kind: '{conf_kind}'}}]->(b);",
            src = cypher_escape(src),
            tgt = cypher_escape(tgt),
            weight = edge.weight,
            line = edge.line,
            confidence = edge.confidence,
        )
        .unwrap();
    }

    std::fs::write(path, buf).expect("write Cypher file");
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use graphify_core::types::{ConfidenceKind, Edge, Language, Node};

    fn make_graph() -> CodeGraph {
        let mut g = CodeGraph::new();
        g.add_node(Node::module(
            "app.main",
            "app/main.py",
            Language::Python,
            1,
            true,
        ));
        g.add_node(Node::module(
            "app.utils",
            "app/utils.py",
            Language::Python,
            1,
            true,
        ));
        g.add_edge("app.main", "app.utils", Edge::imports(3));
        g
    }

    #[test]
    fn write_cypher_creates_file_with_nodes_and_edges() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("graph.cypher");
        let graph = make_graph();

        write_cypher(&graph, &path);

        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("CREATE (:Module {id: 'app.main'"));
        assert!(content.contains("CREATE (:Module {id: 'app.utils'"));
        assert!(content
            .contains("MATCH (a {id: 'app.main'}), (b {id: 'app.utils'}) CREATE (a)-[:IMPORTS"));
        assert!(content.contains("weight: 1"));
    }

    #[test]
    fn write_cypher_includes_confidence_fields() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("graph_conf.cypher");

        let mut g = CodeGraph::new();
        g.add_node(Node::module("a", "a.py", Language::Python, 1, true));
        g.add_node(Node::module("b", "b.py", Language::Python, 1, true));
        g.add_edge(
            "a",
            "b",
            Edge::imports(1).with_confidence(0.85, ConfidenceKind::Inferred),
        );

        write_cypher(&g, &path);

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("confidence: 0.85"));
        assert!(content.contains("confidence_kind: 'Inferred'"));
    }

    #[test]
    fn write_cypher_emits_alternative_paths_as_list_literal() {
        use graphify_core::types::NodeKind;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("graph_alts.cypher");

        let mut g = CodeGraph::new();
        g.add_node(
            Node::symbol(
                "src.entities.Course",
                NodeKind::Class,
                "src/entities/course.ts",
                Language::TypeScript,
                1,
                true,
            )
            .with_alternative_paths(["src.domain.Course", "src.presentation.Course"]),
        );
        g.add_node(Node::module(
            "src.utils",
            "src/utils.ts",
            Language::TypeScript,
            1,
            true,
        ));

        write_cypher(&g, &path);

        let content = std::fs::read_to_string(&path).unwrap();
        // Node with alts gets the property.
        assert!(
            content.contains("alternative_paths: ['src.domain.Course', 'src.presentation.Course']"),
            "Course node should carry alternative_paths list, got:\n{content}"
        );
        // Node without alts does not mention the property — legacy shape
        // preserved.
        let utils_line = content
            .lines()
            .find(|l| l.contains("'src.utils'"))
            .expect("utils line missing");
        assert!(
            !utils_line.contains("alternative_paths"),
            "utils node should not emit empty alts, got: {utils_line}"
        );
    }

    #[test]
    fn cypher_escape_handles_special_chars() {
        assert_eq!(cypher_escape("it's"), "it\\'s");
        assert_eq!(cypher_escape("path\\to\\file"), "path\\\\to\\\\file");
        assert_eq!(cypher_escape("normal"), "normal");
    }

    #[test]
    fn write_cypher_header_contains_counts() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("graph.cypher");
        let graph = make_graph();

        write_cypher(&graph, &path);

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("Nodes: 2, Edges: 1"));
    }
}
